[package]
name = "shuffle"
version = "0.1.0"
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.0.1"
clap = "2.33.0"
failure = "0.1.5"
nom_locate = "1.0.0"
